### ISSUE TITLE
Publish demo website

### ISSUE THREAD

**Issue by Elliot-Alexander** [radix-vue/vaul-vue#19]
- [ ] Pick hosting provider - Github or Cloudflare

**Comment by zernonia** [comment]
Hey @Elliot-Alexander ! Thanks for implementing `vaul-vue`. Do you mind if we transfer this project into a new (wink wink 😉) organization? So that we can publish the doc under a subdomain, and publish npm package under custom scope? (since `vaul-vue`  was taken).

**Comment by Elliot-Alexander** [comment]
Hey @zernonia we definitely can transfer this! We actually managed to get the vaul-vue name. I'll reach out on discord later this afternoon and we can coordinate the transfer :)

**Comment by zernonia** [comment]
https://vaul.unovue.com/
