### ISSUE TITLE
[Feature]: Direction

### ISSUE THREAD

**Issue by preetamslot** [radix-vue/vaul-vue#26]
I know with vaul you can se direction like "left", "right" & "bottom" is this also supported here? thanks

**Comment by zernonia** [comment]
It's not yet support.  Will add this feature soon.

**Comment by khawarizmus** [comment]
Looking forward to this

**Comment by AlexGodbehere** [comment]
Likewise - this will be great when implemented. @zernonia do you have a timescale for this? What can we do to help move this along?

**Comment by andyjamesn** [comment]
Any suggestions on how we could implement this ourselves?
