### ISSUE TITLE
Docs / Static site domain

### ISSUE THREAD

**Issue by Elliot-Alexander** [radix-vue/vaul-vue#4]
We need to get some kind of domain or static hosting for this project. With the intention that it may be grouped in as a dependency that the Radix Vue org helps maintain, are there any considerations we need to make there? Are all of Radix Vue's domains currently registered, hosted etc with a particular provider? Does it help if Vaul Vue does the same?

**Comment by Elliot-Alexander** [comment]
Discussion was started in [this issue here](https://github.com/radix-vue/shadcn-vue/issues/220)

**Comment by zernonia** [comment]
https://vaul.unovue.com/ 😁
